//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faktura()
        {
            this.WydanieZewnetrzneTowaru = new HashSet<WydanieZewnetrzneTowaru>();
        }
    
        public int IdFaktury { get; set; }
        public string Numer { get; set; }
        public Nullable<System.DateTime> DataCzasWystawienia { get; set; }
        public Nullable<int> IdLokazlizacji { get; set; }
        public Nullable<int> IdKontrahenta { get; set; }
        public Nullable<int> IdStanu { get; set; }
        public Nullable<int> Rabat { get; set; }
        public Nullable<int> IdFormyPlatnosci { get; set; }
        public Nullable<int> IdRachunku { get; set; }
        public Nullable<System.DateTime> DataCzasZaksiegowania { get; set; }
        public Nullable<System.DateTime> TerminPlatnosci { get; set; }
        public Nullable<int> IdPracownikaWystawiajacego { get; set; }
        public Nullable<int> IdPracownikaModyfikujacego { get; set; }
        public Nullable<System.DateTime> DataCzasModyfikacji { get; set; }
    
        public virtual FormaPlatnosci FormaPlatnosci { get; set; }
        public virtual Kontrahent Kontrahent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WydanieZewnetrzneTowaru> WydanieZewnetrzneTowaru { get; set; }
    }
}
