//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontrahent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kontrahent()
        {
            this.Faktura = new HashSet<Faktura>();
        }
    
        public int IdKontrahenta { get; set; }
        public string Nazwa { get; set; }
        public Nullable<int> IdRodzajKontrahenta { get; set; }
        public Nullable<int> IdAdresu { get; set; }
        public string NIP { get; set; }
        public string REGON { get; set; }
        public string TelefonKomorkowy1 { get; set; }
        public string TelefonKomorkowy2 { get; set; }
        public Nullable<int> IdPracownikaModyfikujacego { get; set; }
        public Nullable<System.DateTime> DataCzasModyfikacji { get; set; }
        public string Uwagi { get; set; }
    
        public virtual Adres Adres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktura> Faktura { get; set; }
        public virtual RodzajKontrahenta RodzajKontrahenta { get; set; }
    }
}
