//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PDABEntities1 : DbContext
    {
        public PDABEntities1()
            : base("name=PDABEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adres> Adres { get; set; }
        public virtual DbSet<Faktura> Faktura { get; set; }
        public virtual DbSet<FormaPlatnosci> FormaPlatnosci { get; set; }
        public virtual DbSet<JednostkaMiaryTowaru> JednostkaMiaryTowaru { get; set; }
        public virtual DbSet<Kontrahent> Kontrahent { get; set; }
        public virtual DbSet<PozycjaPrzyjeciaZewnetrznegoTowaru> PozycjaPrzyjeciaZewnetrznegoTowaru { get; set; }
        public virtual DbSet<PozycjaWydaniaZewnetrznegoTowaru> PozycjaWydaniaZewnetrznegoTowaru { get; set; }
        public virtual DbSet<Pracownicy> Pracownicy { get; set; }
        public virtual DbSet<PracownicyTask> PracownicyTask { get; set; }
        public virtual DbSet<PrzyjecieZewnetrzneTowaru> PrzyjecieZewnetrzneTowaru { get; set; }
        public virtual DbSet<RodzajKontrahenta> RodzajKontrahenta { get; set; }
        public virtual DbSet<StawkiVatZakupu> StawkiVatZakupu { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Towar> Towar { get; set; }
        public virtual DbSet<TowarJednostkaMiaryTowaru> TowarJednostkaMiaryTowaru { get; set; }
        public virtual DbSet<WydanieZewnetrzneTowaru> WydanieZewnetrzneTowaru { get; set; }
        public virtual DbSet<ZmianaCenyTowaru> ZmianaCenyTowaru { get; set; }
    }
}
