//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrzyjecieZewnetrzneTowaru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrzyjecieZewnetrzneTowaru()
        {
            this.PozycjaPrzyjeciaZewnetrznegoTowaru = new HashSet<PozycjaPrzyjeciaZewnetrznegoTowaru>();
        }
    
        public int IdPrzyjeciaZewnetrznego { get; set; }
        public Nullable<System.DateTime> DataCzasPrzyjecia { get; set; }
        public Nullable<System.DateTime> DataCzasZatwierdzenia { get; set; }
        public Nullable<int> IdPracownikaWystawiajacego { get; set; }
        public Nullable<int> IdPracownikaZatwierdzajacego { get; set; }
        public Nullable<int> IdPracownikaPrzyjmujacego { get; set; }
        public Nullable<int> IdKontrahenta { get; set; }
        public Nullable<int> IdZamowienia { get; set; }
        public string Numer { get; set; }
        public string Uwagi { get; set; }
        public Nullable<int> IdPracownikaModyfikujacego { get; set; }
        public Nullable<System.DateTime> DataCzasModyfikacji { get; set; }
        public bool CzyAktywny { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjaPrzyjeciaZewnetrznegoTowaru> PozycjaPrzyjeciaZewnetrznegoTowaru { get; set; }
        public virtual PracownicyTask PracownicyTask { get; set; }
    }
}
