//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Towar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Towar()
        {
            this.PozycjaPrzyjeciaZewnetrznegoTowaru = new HashSet<PozycjaPrzyjeciaZewnetrznegoTowaru>();
            this.PozycjaWydaniaZewnetrznegoTowaru = new HashSet<PozycjaWydaniaZewnetrznegoTowaru>();
            this.TowarJednostkaMiaryTowaru = new HashSet<TowarJednostkaMiaryTowaru>();
        }
    
        public int IdProduktu { get; set; }
        public Nullable<int> Kod { get; set; }
        public Nullable<int> IdKategorii { get; set; }
        public string Nazwa { get; set; }
        public Nullable<int> IdPracownikaDodajacego { get; set; }
        public Nullable<int> IdPracownikaModyfikujacego { get; set; }
        public Nullable<int> IdPracownikaKasujacego { get; set; }
        public Nullable<System.DateTime> DataCZasDodania { get; set; }
        public Nullable<System.DateTime> DataCzasModyfikacji { get; set; }
        public Nullable<System.DateTime> DataCzasKasowania { get; set; }
        public string Uwagi { get; set; }
        public bool CzyAktywny { get; set; }
        public Nullable<int> Ilosc { get; set; }
        public Nullable<int> IdPrzyjeciaZewnetrznego { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjaPrzyjeciaZewnetrznegoTowaru> PozycjaPrzyjeciaZewnetrznegoTowaru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjaWydaniaZewnetrznegoTowaru> PozycjaWydaniaZewnetrznegoTowaru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TowarJednostkaMiaryTowaru> TowarJednostkaMiaryTowaru { get; set; }
    }
}
