//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WydanieZewnetrzneTowaru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WydanieZewnetrzneTowaru()
        {
            this.PozycjaWydaniaZewnetrznegoTowaru = new HashSet<PozycjaWydaniaZewnetrznegoTowaru>();
        }
    
        public int IdWydaniaZewnetrznegoTowaru { get; set; }
        public Nullable<System.DateTime> DataCzasWydania { get; set; }
        public Nullable<System.DateTime> DataCzasZatwierdzenia { get; set; }
        public Nullable<System.DateTime> DataCzasOdebrania { get; set; }
        public Nullable<int> IdPracownikaWystawiajacego { get; set; }
        public Nullable<int> IdPracownikaZatwierdzajacego { get; set; }
        public Nullable<int> IdPracownikaWydajacego { get; set; }
        public Nullable<int> IdKontrahenta { get; set; }
        public string Numer { get; set; }
        public Nullable<int> IdFaktury { get; set; }
        public string Uwagi { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
        public Nullable<int> IdProduktu { get; set; }
    
        public virtual Faktura Faktura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjaWydaniaZewnetrznegoTowaru> PozycjaWydaniaZewnetrznegoTowaru { get; set; }
    }
}
