//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZmianaCenyTowaru
    {
        public int IdZmianaCenyTowaru { get; set; }
        public Nullable<int> IdJednostkiMiaryTowaru { get; set; }
        public Nullable<System.DateTime> DataCzasObowiazywaniaOd { get; set; }
        public Nullable<System.DateTime> DataCzasObowiazywaniaDo { get; set; }
        public Nullable<int> CenaNettoSprzedazyTowaru { get; set; }
    
        public virtual JednostkaMiaryTowaru JednostkaMiaryTowaru { get; set; }
    }
}
